version: '3.7'

services:
  mysql:
    image: mysql:5
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file: .env
  
  magento2:
    depends_on:
      - mysql
    build: 
      context: .
      args: 
        - magento_username=$magento_username
        - magento_password=$magento_password
    image: paystack-magento2
    ports:
      - "8000:80"
    links:
      - mysql
    env_file: .env
volumes:
  db_data: {}
